### ISSUE TITLE
Сделать rtl  для ввода арабских симолов.

### ISSUE THREAD

**Issue by Valyukhov** [texttree/notepad-rcl#42]
Надо обновить несолько компонентов.
1. Нужно проверять, когда вводятся арабские символы - если есть хоть 1 арабский символ или все - то делать дирекшен rtl
2. Нужно проверять, если значение приходит. Допустим как в компоненте Treeview - часть названий могут быть на арабском, а часть нет.
вот пример
https://codepen.io/vsync/pen/qBNbmy

**Comment by foxprogs** [comment]
Кстати, есть такой момент. К примеру словарная статья на какое-то слово. И там написано "на иврите это слово ... означает то-то"
Будет одно слово на иврите, это значит что он весь текст перевернет справа налево? Может какой-то другой ориентир лучше поискать? К примеру больше половины
